Source.create(name: "TechCrunch", api_id: "techcrunch", image_url: "http://i.newsapi.org/techcrunch-m.png")
Source.create(name: "National Geographic", api_id: "national-geographic", image_url: "http://i.newsapi.org/national-geographic-m.png")
Source.create(name: "IGN", api_id: "ign", image_url: "http://i.newsapi.org/ign-m.png")
Source.create(name: "Time", api_id: "time", image_url: "http://i.newsapi.org/time-m.png")
Source.create(name: "Metro", api_id: "metro", image_url: "http://i.newsapi.org/metro-m.png")
Source.create(name: "CNN", api_id: "cnn", image_url: "http://i.newsapi.org/cnn-m.png")

Source.create(name: "TechCrunch", api_id: "techcrunch", image_url: "http://i.newsapi.org/techcrunch-m.png")
Source.create(name: "National Geographic", api_id: "national-geographic", image_url: "http://i.newsapi.org/national-geographic-m.png")
Source.create(name: "IGN", api_id: "ign", image_url: "http://i.newsapi.org/ign-m.png")
Source.create(name: "Time", api_id: "time", image_url: "http://i.newsapi.org/time-m.png")
Source.create(name: "Metro", api_id: "metro", image_url: "http://i.newsapi.org/metro-m.png")
Source.create(name: "CNN", api_id: "cnn", image_url: "http://i.newsapi.org/cnn-m.png")